version: '3.4'

services:
  discordbotdashboardv2:
    image: discordbotdashboardv2
    build:
      context: src
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
